### ISSUE TITLE
Help-view CSS

### ISSUE THREAD

**Issue by emmariaolsson** [johanmoritz/heard-when-vue3#51]
- [x]  Matching theme as rest of app (perhaps black with white text)
- [x]  Centered text-alignment
- [x] Make exit-button round
- [x] Update sceenshots when app is done (prio)
- [x] Read through text to see if anything is missing

**Comment by axelmjohansson** [comment]
Jag tyckte att det blev svårare att läsa texten när den centrerades, ändrade tillbaka.
