### ISSUE TITLE
Choice should not be displayed in the beginning of a player's turn

### ISSUE THREAD

**Issue by emmariaolsson** [johanmoritz/heard-when-vue3#57]
Right now, you have to choose "Draw" or "Lock" in order to start guessing. Since there is nothing to lock this is a bit unintuitive. Add condition to only show ChoiceView guessesMadeThisTurn !== 0. This means there has to be a slightly different event-flow in the backend to allow for a guess without having made a choice.

**Comment by emmariaolsson** [comment]
In domain.ts
```
const validTransitions: TransitionTable = {
    newTurn: {
      nextEvent: "listen" <-----
    },
    pass: {
      passEvent: "newTurn",
    },
    choice: {
      drawAction: "draw",
      passAction: "pass",
    },
    draw: {
      drawEvent: "listen",
    },
    listen: {
      guessAction: "evaluation",
    },
    evaluation: {
      wrongEvent: "newTurn",
      correctEvent: "choice" <-----
    }
```

Suggested change. Could this solve the problem @johanmoritz ?

**Comment by johanmoritz** [comment]
Nope, sadly there is no simple way in the backend to know when a players turn start. numberOfGuesses refers to how many players have guessed a particular card.
