### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by emmariaolsson** [johanmoritz/heard-when-vue3#62]
- Buttons look different for iOS and Android
- Scroll through cards so they aren't cut off on overflow
- Music player is too big
- Can't guess before and after (the leftest or rightest buttons) when too many cards
- Consider having guess buttons visible all the time for mobile users

**Comment by axelmjohansson** [comment]
Cannot scroll fully to the left if too many cards are displayed.

Add scrollbar to own cards when OtherPlayer
